# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce69b4757a194244b1c1254e85b02b48770b0d74bbe4991f469c62446c8e9939d20aa924c2b79d9054f040061552f81128d2a27a060769149b3f3cb0c8bab3c0

test:
  secret_key_base: 19e543af1842812d74fa646deb9cddb792eaa6295c0e0777d3804b0400f85fd107ea3e11a00a8b95526608505e5b6021bf91e40f0b1e60c3d790b01718bb47ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
